spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: userdb
    password: pass
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
#    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - health
          - logfile
          - hystrix.stream
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

server:
  port: 8080

logging:
  level:
    root: info
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} %-5level %msg%n'
  file:
    name: 'logs/app.log'