spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: userdb
    password: pass

  sql:
    init:
      mode: always
      #      never
      #      always
      data-locations: data.sql
      schema-locations: schema.sql